#spring:
#  freemarker:
#    template-loader-path: classpath:/templates/
#    prefer-file-system-access: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 15000
server:
  port: 8761
#logging:
#  level:
#    org:
#      springframework: DEBUG